/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.versioncode;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;

import android.content.Context;
import android.content.pm.PackageInfo;
import android.content.pm.PackageManager.NameNotFoundException;

@Kroll.module(name = "Versioncode", id = "ti.versioncode")
public class AppinfoModule extends KrollModule {
	public AppinfoModule() {
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {
	}

	@Kroll.method
	public static KrollDict get() {
		KrollDict kd = new KrollDict();
		int versionCode = 0;
		long firstInstallTime = 0;
		String versionName = null;
		Context ctx = TiApplication.getInstance().getApplicationContext();
		try {
			PackageInfo pInfo = ctx.getPackageManager().getPackageInfo(
					TiApplication.getInstance().getApplicationContext()
							.getPackageName(), 0);
			firstInstallTime = pInfo.firstInstallTime;
			kd.put("versionsCode", pInfo.versionCode);
			kd.put("firstInstallTime", firstInstallTime);
			kd.put("versionName", pInfo.versionName);
			kd.put("lastUpdateTime", pInfo.lastUpdateTime);
			kd.put("requestedPermissions", pInfo.requestedPermissions);

			return kd;

		} catch (NameNotFoundException e) {
			e.printStackTrace();
		}
		return null;

	}
}
