/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.appinfo;

import java.text.SimpleDateFormat;
import java.util.GregorianCalendar;
import java.util.Locale;
import java.util.TimeZone;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.titanium.TiApplication;

import android.content.Context;
import android.content.pm.ApplicationInfo;
import android.content.pm.PackageInfo;
import android.content.pm.PackageManager.NameNotFoundException;

@Kroll.module(name = "Appinfo", id = "ti.appinfo")
public class AppinfoModule extends KrollModule {
	private static final String LCAT = "AppInfo";
	private static SimpleDateFormat sdf = new SimpleDateFormat(
			"yyyy-MM-dd HH:mm:ss,SSS", Locale.US);

	public AppinfoModule() {
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {
		init();
	}

	@Kroll.method
	public KrollDict getAll() {
		KrollDict appinfo = init();
		return appinfo;
	}

	@Kroll.method
	public String getBackupAgentName() {
		KrollDict appinfo = init();
		if (appinfo == null)
			return null;
		return appinfo.getKrollDict("appinfo").getString("backupAgentName");
	}

	@Kroll.method
	public String getDataDir() {
		KrollDict appinfo = init();
		if (appinfo == null)
			return null;
		return appinfo.getKrollDict("appinfo").getString("dataDir");
	}

	@Kroll.method
	public String getNativeLibraryDir() {
		KrollDict appinfo = init();
		if (appinfo == null)
			return null;
		return appinfo.getKrollDict("appinfo").getString("nativeLibraryDir");
	}

	@Kroll.method
	public String getSharedLibraryFiles() {
		KrollDict appinfo = init();
		if (appinfo == null)
			return null;
		return appinfo.getKrollDict("appinfo").getString("sharedLibraryFiles");
	}

	@Kroll.method
	public String getName() {
		KrollDict appinfo = init();
		if (appinfo == null)
			return null;
		KrollDict kd = appinfo.getKrollDict("appinfo");
		if (kd != null)
			return kd.getString("name");
		else
			return null;
	}

	@Kroll.method
	public int getVersionsCode() {
		KrollDict appinfo = init();
		if (appinfo == null)
			return 0;
		return appinfo.getInt("versionsCode");
	}

	private static String time2date(long time) {
		GregorianCalendar calendar = new GregorianCalendar(
				TimeZone.getTimeZone("US/Central"));
		calendar.setTimeInMillis(time);
		return sdf.format(calendar.getTime());
	}

	private static KrollDict init() {
		KrollDict appinfo = new KrollDict();
		Context ctx = TiApplication.getInstance().getApplicationContext();
		try {
			PackageInfo pInfo = ctx.getPackageManager().getPackageInfo(
					TiApplication.getInstance().getApplicationContext()
							.getPackageName(), 0);
			ApplicationInfo appInfo = pInfo.applicationInfo;
			KrollDict ai = new KrollDict();
			ai.put("backupAgentName", appInfo.backupAgentName);
			ai.put("dataDir", appInfo.dataDir);
			ai.put("name", appInfo.name);
			ai.put("nativeLibraryDir", appInfo.nativeLibraryDir);
			ai.put("sharedLibraryFiles", appInfo.sharedLibraryFiles);
			appinfo.put("appInfo", ai);
			appinfo.put("sharedUserId", pInfo.sharedUserId);
			appinfo.put("versionsCode", pInfo.versionCode);
			appinfo.put("firstInstallTime", pInfo.firstInstallTime);
			appinfo.put("firstInstallDate", time2date(pInfo.firstInstallTime));
			appinfo.put("lastUpdateTime", pInfo.lastUpdateTime);
			appinfo.put("versionName", pInfo.versionName);
			appinfo.put("requestedPermissions", pInfo.requestedPermissions);
			Log.d(LCAT + "////////////////////////////////////////////\n",
					appinfo.toString());
			return appinfo;
		} catch (NameNotFoundException e) {
			e.printStackTrace();
			return null;
		}
	}
}
